In [19]:
#Student Marks Analysis
import numpy as np

Marks = np.array([
    [85, 78, 90],
    [60, 65, 70],
    [95, 88, 92],
    [45, 50, 55],
    [72, 80, 75]
])
#print(Marks)
#print(Marks[2,1])# tells location
#print(Marks.shape) #tells size
#print(Marks.ndim) #tells how many dimensions
#print(Marks.dtype) #tells the data type of element
#print(Marks[0]) # returns first students marks
#print(Marks[-1])# returns last students marks
#print(Marks[:,0] >60)# returns more than 60 marks from first column
#print(Marks[0,:])# returns all values from first rows means all marks for first student
math_marks = Marks[:, 1]
print(math_marks[math_marks > 75])
print(math_marks)


[78 88 80]
[78 65 88 50 80]


In [9]:
import numpy as np

data = np.array([[[1, 2, 3], [4, 5, 6]]])
print(data)
print(np.ndim(data)) #tells how many dimensions
print(data.shape) #tells the shape of the array

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)


In [16]:
import numpy as np
a = np.array([[[42],[56]]])
print(a.ndim) #tells how many dimensions
print(a.shape) #tells the shape of the array

3
(1, 2, 1)


In [ ]:
#4D array
import numpy as np
data = np.array([[[[31, 22, 93],
                   [43, 53, 69],
                   [13, 22, 39],
                   [34, 56, 69]]]])
print(data.ndim)
print(data.shape)      
print(data.dtype)             

4
(1, 1, 4, 3)
int64


In [ ]:
#Reshaping an array
import numpy as np 
a = np.array([1,2,3,4,4,5,5,6,7,7,8,9,9,10,11,12])
print(a.ndim)
new_arr = a.reshape(4,4)
print(new_arr)

1
[[ 1  2  3  4]
 [ 4  5  5  6]
 [ 7  7  8  9]
 [ 9 10 11 12]]


In [ ]:
#Array broadcasting
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = a*b 
print(c)

[ 42  84 126 168 210]


In [35]:
#Creating an array with a range of values
import numpy as np
a = np.arange(0, 10, 2)
print(a)
print(a.ndim)

[0 2 4 6 8]
1


In [34]:
from numpy import random
#Generate a random integer between 0 and 10
x = random.rand(1,10)
print(x)

[[0.6252982  0.33260333 0.58706879 0.4012155  0.57285994 0.9141138
  0.75819506 0.91436413 0.609291   0.95078617]]


In [29]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a.size)

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))


6
21
1
6
3.5
3.5
1.707825127659933


In [16]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a, axis=0))  # Sum along columns
print(np.sum(a, axis=1))  # Sum along rows


[5 7 9]
[ 6 15]


In [ ]:
#Creating an array of zeros
import numpy as np
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
import numpy as np 
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
import numpy as np
import pandas as pd

data = {
    'Name': ['Ankit', 'Rahul', 'Sonia', 'Raju','Bheem'],
    'Marks/100': [85, 34, 95, 36, 80]
}

df = pd.DataFrame(data)

df['Result'] = np.where(df['Marks/100'] < 35, 'Re-Exam',
                        np.where(df['Marks/100'] > 90, 'Topper', 'Pass'))
print(df)


    Name  Marks/100   Result
0  Ankit         85     Pass
1  Rahul         34  Re-Exam
2  Sonia         95   Topper
3   Raju         36     Pass
4  Bheem         80     Pass
